name: Build & Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install deps
              run: |
                  pip install nuitka PyQt6

            - name: Build Linux binary
              run: |
                  chmod +x build.sh
                  VERSION=${GITHUB_REF_NAME} ./build.sh

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: linux-build
                  path: dist/*

    build-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install deps
              run: |
                  pip install nuitka PyQt6

            - name: Build Windows binary
              shell: bash
              run: |
                  VERSION=${GITHUB_REF_NAME} ./build.sh

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows-build
                  path: dist/*

    build-macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install deps
              run: |
                  pip install nuitka PyQt6

            - name: Build macOS binary
              run: |
                  chmod +x build.sh
                  VERSION=${GITHUB_REF_NAME} ./build.sh

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: macos-build
                  path: dist/*
